---
- hosts: all
  roles:
    - role: oci-rsa-ansible-base
      become: true
    - role: wazuh-ansible/wazuh-ansible/roles/wazuh/ansible-wazuh-agent
      become: true
    - role: bastion
      become: true
    - role: oci-rsa-ansible-base/wazuh_agent_configuration
      become: true
