---
- hosts: all
  vars_files:
    - ../extra-variables.yml
  roles:
    - role: oci-rsa-ansible-base
      become: true
    - role: geerlingguy.clamav
      become: true
    - role: bastion
      become: true